name: 'notifications-service'
services:
  notifications-service:
    container_name: notifications-service
    environment:
      KAFKA_URLS: "kafka:19092"
      KAFKA_GROUP_ID: game-events-consumer
      KAFKA_CLIENT_ID: game-notifier
      KAFKA_RETRIES: 3
      KAFKA_REQUEST_TIMEOUT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart:
      on-failure:3
    build:
      context: .
    depends_on:
      - redis
      - kafka
  zookeeper:
    image: 'zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - './volumes/kafka/data/zookeeper/data:/data'
      - './volumes/kafka/data/zookeeper/datalog:/datalog'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
    volumes:
      - './volumes/kafka/data/kafka/data:/var/lib/kafka/data'
    ports:
      - '9092:9092'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    ports:
      - '8080:8080'
    depends_on:
      - kafka
