version: '3.8'
name: 'notifications-service'
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    env_file:
      - docker-env
    ports:
      - "9094:9094"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"