export enum EventType {
  PLAYER_LEVEL_UP = 'PLAYER_LEVEL_UP',
  ITEM_ACQUIRED = 'ITEM_ACQUIRED',
  FRIEND_REQUEST_SENT = 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
}
